# Python-Wiederholung
(c) 2023 by Harald Bögeholz

**Aufgabe 1:** Schreibe ein Programm, das die Quadratzahlen x^2 für x von 1 bis 10 ausgibt, also:
```
1
4
9
25
...
100
```

In [106]:
for i in range(1, 11):
    print(i*i)

1
4
9
16
25
36
49
64
81
100


**Achtung:** Wenn wir Zahlen bis 10 wollen, müssen wir `range(1, 11)` schreiben. `range(10)` dagegen erzeugt die Zahlen von 0 bis 9.

**Aufgabe 2:** Schreibe ein Programm, das eine Multiplikationstabelle ausgibt:
```
1 2 3 4 5 6 7 8 9 10
2 4 6 8 10 ... 20
...
10 20 ... 100
```
Du brauchst zwei ineinander geschachtelte `for`-Schleifen.
Tipp: `print(x, end="")` gibt x aus, ohne eine neue Zeile anzufangen. `print()` fängt eine neue Zeile an.

In [107]:
for i in range(1,11):
    for j in range(1,11):
        print(i*j, end=" ")
    print()

1 2 3 4 5 6 7 8 9 10 
2 4 6 8 10 12 14 16 18 20 
3 6 9 12 15 18 21 24 27 30 
4 8 12 16 20 24 28 32 36 40 
5 10 15 20 25 30 35 40 45 50 
6 12 18 24 30 36 42 48 54 60 
7 14 21 28 35 42 49 56 63 70 
8 16 24 32 40 48 56 64 72 80 
9 18 27 36 45 54 63 72 81 90 
10 20 30 40 50 60 70 80 90 100 


In [108]:
a = [2., 17., 42., 3., 5., 7., 100., 50.]

**Aufgabe 2.9:** Schreibe eine `for`-Schleife, die jede Zahl der Liste `a` in einer eigenen Zeile ausgibt.

In [109]:
a[1]

17.0

In [110]:
for i in range(len(a)):
    print(a[i])

2.0
17.0
42.0
3.0
5.0
7.0
100.0
50.0


Oder:

In [111]:
for x in a:
    print(x)

2.0
17.0
42.0
3.0
5.0
7.0
100.0
50.0


**Aufgabe 3:** Berechne die Summe der Zahlen in der Liste `a`. Ausnahmsweise, nur zur Übung: Bitte verwende nicht die Funktion `sum()`, sondern eine `for`-Schleife!

In [112]:
total = 0.0
for i in range(len(a)):
    total += a[i]
total

226.0

Oder:

In [113]:
total = 0.0
for x in a:
    total += x
total

226.0

**Aufgabe 4:** Berechne den Mittelwert der Zahlen in der Liste `a`. Verwende keine vorgefertigte Funktion, sondern wieder eine `for`-Schleife! $$ \bar{a} := \frac{1}{n}\sum_{i=1}^n a_i $$

In [114]:
total = 0.0
for i in range(len(a)):
    total += a[i]
average = total / len(a)
average

28.25

**Aufgabe 5:** Berechne die Standardabweichung (standard deviation) der Zahlen in der Liste `a`. Verwende keine vorgefertigte Funktion! $$\sigma := \sqrt{\frac{1}{n}\sum_{i=1}^n (a_i - \bar{a})^2}$$

In [115]:
from math import sqrt # Quadratwurzel
total = 0.0
for i in range(len(a)):
    total += a[i]
average = total / len(a)
ss = 0.0
for i in range(len(a)):
    ss += (a[i] - average) ** 2
std_dev = sqrt( ss / len(a) )
std_dev

32.123784023679406

**Aufgabe 6:** Betrachte die Liste `a` als Vektor. Berechne die Länge des Vektors.

Die Länge eines Vektors ist wie folgt definiert:
$$ \lVert a \rVert := \sqrt{\sum_{i=1}^n a_i^2} $$

In [116]:
square_sum = 0.0
for i in range(len(a)):
    square_sum += a[i] ** 2
norm = sqrt(square_sum)
norm

120.9958676980334

## Hintergrund-Info

Die Länge eines Vektors wird auch als *Norm* bezeichnet. Wenn nichts anderes gesagt wird, versteht man unter der Norm die sogenannte *euklidische Norm* oder $\ell^2$-Norm, ausgeschrieben $\lVert a \rVert_2$.

Es gibt auch andere Normen. Die $\ell^1$-Norm, auch *Manhattan-Distanz* genannt, ist wie folgt definiert:
$$\lVert a \rVert_1 = \sum_{i=1}^n |a_i|$$

Die *Supremumsnorm* $\ell^\infty$ ist wie folgt definiert:
$$\lVert a \rVert_\infty = \max_i |a_i|$$

## Das Ganze mit numpy:

In [117]:
A = np.array(a)
A

array([  2.,  17.,  42.,   3.,   5.,   7., 100.,  50.])

Mittelwert (average, mean):

In [118]:
A.mean()

28.25

Standardabweichung (standard deviation):

In [119]:
A.std()

32.123784023679406

Länge eines Vektors (euklidische Norm):

In [120]:
np.linalg.norm(A)

120.9958676980334

In [121]:
A

array([  2.,  17.,  42.,   3.,   5.,   7., 100.,  50.])

Wenn wir von unserer Liste den Mittelwert abziehen und dann durch die Standardabweichung dividieren, erhalten wir eine neue, skalierte Liste, deren Mittelwert 0 und deren Standardabweichung 1 ist:

In [122]:
A0 = (A - A.mean()) / A.std()
A0

array([-0.81715155, -0.35020781,  0.42803177, -0.78602197, -0.7237628 ,
       -0.66150364,  2.23354758,  0.67706843])

In [123]:
A0.mean()

-2.7755575615628914e-17

In [124]:
A0.std()

0.9999999999999999